title: Potters Jekyll based musings
author: Fabulous
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is an awesome site with the random Rum-based thoughts of someone trying to learn something new.  It is amazing it will give you everything you ever need to know in life

# social links
twitter_username: Idonthaveone# DO NOT include the @ character, or else the build will fail!
github_username:  spotter-boop# DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
